lang: ja
# project_id: 1099396857
project_id: 843162693

colors:
  reset: "0m" # default
  log: "36m" # cyan
  info: "32m" # green
  warning: "33m" # yellow
  error: "31m" # red
  debug: "34m" # blue
  success: "92m" # bright green
  critical: "95m" # magenta
  note: "35m" # purple
  yellow: "220m"

logs:
  timestamp: true
  output:
    directory: ./logs
    format: "<level> <timestamp> <message>"
  on_set:
    format: "変数 <var> は、<timestamp> に値 <value> に設定されました"
    colors:
      var: "critical"
      value: "success"
      timestamp: "log"
  on_del:
    format: "<user> が変数 <var> を削除しました"
    colors:
      var: "warning"
  on_create:
    format: "<user> が変数 <var> を作成しました"
    colors:
      var: "success"
  on_ready:
    message: "イベントリスナーの準備ができました！"

console:
  log:
    color:
      level: '<log>'
      message: '@none'
      timestamp: '@none'
    format: "<level> <timestamp> <message>"
  info:
    color:
      level: '<info>'
      message: '@none'
      timestamp: '@none'
    format: "<level> <timestamp> <message>"
  warning:
    color:
      level: '<warning>'
      message: '<warning>'
      timestamp: '<warning>'
    format: "<level> <timestamp> <message>"
  error:
    color:
      level: '<error>'
      message: '<error>'
      timestamp: '<error>'
    format: "<level> <timestamp> <message>"
  debug:
    color:
      level: '<debug>'
      message: '@none'
      timestamp: '@none'
    format: "<level> <timestamp> <message>"

alert:
  on_set:
    reset_interval: 1 # リセット間隔
    update_threshold: 5 # 許容回数
    output_log: false
    format: "Event <event_type> by <key> exceeded the threshold (<threshold> times). Current: <count> times in <interval> seconds"
  on_del:
    reset_interval: 1
    update_threshold: 1
    output_log: false
    format: "Event <event_type> by <key> exceeded the threshold (<threshold> times). Current: <count> times in <interval> seconds"
  on_create:
    reset_interval: 1
    update_threshold: 1
    output_log: false
    format: "Event <event_type> by <key> exceeded the threshold (<threshold> times). Current: <count> times in <interval> seconds"